// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: evtc_rpc.proto

#include "evtc_rpc.pb.h"
#include "evtc_rpc.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace evtc_rpc {

class Mockevtc_rpcStub : public evtc_rpc::StubInterface {
 public:
  MOCK_METHOD1(ConnectRaw, ::grpc::ClientReaderWriterInterface< ::evtc_rpc::Message, ::evtc_rpc::Message>*(::grpc::ClientContext* context));
  MOCK_METHOD3(AsyncConnectRaw, ::grpc::ClientAsyncReaderWriterInterface<::evtc_rpc::Message, ::evtc_rpc::Message>*(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD2(PrepareAsyncConnectRaw, ::grpc::ClientAsyncReaderWriterInterface<::evtc_rpc::Message, ::evtc_rpc::Message>*(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq));
};

} // namespace evtc_rpc

